<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Final Project</title>

<script src="site_libs/header-attrs-2.24/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<link href="site_libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="site_libs/leaflet-1.3.1/leaflet.js"></script>
<link href="site_libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="site_libs/proj4-2.6.2/proj4.min.js"></script>
<script src="site_libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="site_libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="site_libs/leaflet-binding-2.2.1/leaflet.js"></script>
<script src="site_libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="site_libs/leaflet-providers-plugin-2.2.1/leaflet-providers-plugin.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="data_visualization.html">Data Visualization</a>
</li>
<li>
  <a href="interactive_maps.html">Interactive Maps</a>
</li>
<li>
  <a href="statistical_models.html">Statistical Models</a>
</li>
<li>
  <a href="mailto:&lt;anw2158@cumc.columbia.edu,jwc2177@cumc.columbia.edu, zq2227@cumc.columbia.edu, yc4382@cumc.columbia.edu, td2809@cumc.columbia.edu &gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-github fa-lg"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="https://github.com/JakeWColdiron/p8105_final_project/">Data Cleaning Repository</a>
    </li>
    <li>
      <a href="https://github.com/AungNWin/nychivreport.github.io">Website Repository</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Final Project</h1>

</div>


<div id="new-york-city-hivaids-report" class="section level3">
<h3><strong>New York City HIV/AIDS Report</strong></h3>
<p><strong>A HIV Epidemiological report aimed to investigate the
correlation between HIV infection and socioeconomic status, population
distribution, and medical resources in New York City.</strong></p>
<center>
<img src="images/hiv.png" style="width:75%" class="center">
</center>
</div>
<div id="motivation" class="section level3">
<h3>Motivation</h3>
<p>HIV/AIDS are still a significant public health challenge,in 2020,
there were 100,712 people living with HIV in New York City. The vast
population diversity and economic disparities of New York City, provide
a unique landscape for studying how socioeconomic status, population
distribution, and medical resources intersect to influence HIV infection
rates within the in a dense urban environment city. The medical resource
and economic status distribution often varies greatly across different
boroughs and neighborhoods in nyc.Investigating how these disparities
relate to HIV prevalence can shed light on the broader implications of
socioeconomic on epidemiology and develop more targeted intervention
strategies base on the different demographics condition.</p>
</div>
<div id="screencast" class="section level3">
<h3>Screencast</h3>
</div>
<div id="collaborators" class="section level3">
<h3>Collaborators</h3>
<ul>
<li>Jake W. Coldiron(jwc2177)</li>
<li>Zixuan Qiu(qiu2227)</li>
<li>Tianyuan Deng(td2809)</li>
<li>Aung Nay Win(anw2158)</li>
<li>Yuqi Cheng(yc4382)</li>
</ul>
</div>
<div id="data" class="section level3">
<h3>Data</h3>
<p>To prepare the data analysis, we load these following libraries:</p>
<ul>
<li><code>tidyverse</code></li>
<li><code>rvest</code></li>
<li><code>httr</code></li>
<li><code>plotly</code></li>
<li><code>ggplot2</code></li>
<li><code>leaflet</code></li>
<li><code>caret</code></li>
</ul>
<pre class="r"><code>library(tidyverse)
library(rvest)
library(httr)
library(plotly)
library(ggplot2)
library(leaflet)
library(caret)</code></pre>
</div>
<div id="data-processing" class="section level1">
<h1>Data processing</h1>
<p>The datasets used in this study were sourced from the NYC OpenData
portal, a public platform offering diverse datasets from New York City
agencies. We utilized the R programming language, employing the
<code>httr</code> package to perform HTTP GET requests for retrieving
the data. Specifically, two datasets, <code>nyc_HIV1</code> and
<code>nyc_HIV2</code>, were accessed from distinct URLs with set record
limits of 10,000 and 22,000 respectively. These datasets, containing
information on HIV statistics, were parsed and filtered to include data
from the year 2017 onwards. Additionally, a dataset for HIV service
resources, <code>HIV_service</code>, was similarly obtained with a
record limit of 1,000. This dataset was processed to select critical
columns like facility information and geographical coordinates. This
process ensured a comprehensive and tailored extraction of data
pertinent to our analysis of HIV trends and resources in New York
City.</p>
<p>We input the New York HIV data from NYC opendata</p>
<pre class="r"><code>nyc_HIV1=
  GET(&quot;https://data.cityofnewyork.us/resource/ykvb-493p.csv&quot;,
  query = list(&quot;$limit&quot; = 10000)) |&gt;
  content(&quot;parsed&quot;)|&gt;
  filter(year &gt;= 2017)


nyc_HIV2=
  GET(&quot;https://data.cityofnewyork.us/resource/dxnu-p2qd.csv&quot;,
  query = list(&quot;$limit&quot; = 22000)) |&gt;
  content(&quot;parsed&quot;)|&gt;
  filter(year &gt;= 2017)</code></pre>
<p>And input HIV service resource data</p>
<pre class="r"><code>HIV_service=
  GET(&quot;https://data.cityofnewyork.us/resource/pwts-g83w.csv&quot;,
  query = list(&quot;$limit&quot; = 1000)) |&gt;
  content(&quot;parsed&quot;)|&gt;
  select(unique_id,facilityname,service_type, address,borough,state,zipcode,latitude,longitude)</code></pre>
<p><strong>Calculate the sum, mean, median, standard deviation of
HIV/AIDS indicators</strong></p>
<pre class="r"><code>colnames(nyc_HIV1)</code></pre>
<pre><code>##  [1] &quot;year&quot;                          &quot;borough&quot;                      
##  [3] &quot;neighborhood&quot;                  &quot;sex&quot;                          
##  [5] &quot;race&quot;                          &quot;hiv_diagnoses_num&quot;            
##  [7] &quot;hiv_diagnoses_num_per_100k&quot;    &quot;hiv_aids_concurrent_num&quot;      
##  [9] &quot;concurrent_hiv_aids_among_all&quot; &quot;aids_diagnoses_num&quot;           
## [11] &quot;aids_diagnoses_num_per_100k&quot;</code></pre>
<pre class="r"><code>colnames(nyc_HIV2)</code></pre>
<pre><code>##  [1] &quot;year&quot;                          &quot;neighborhood&quot;                 
##  [3] &quot;race&quot;                          &quot;age&quot;                          
##  [5] &quot;hiv_diagnoses_num&quot;             &quot;hiv_diagnoses_num_per_100k&quot;   
##  [7] &quot;hiv_aids_concurrent_num&quot;       &quot;concurrent_hiv_aids_among_all&quot;
##  [9] &quot;aids_diagnoses_num&quot;            &quot;aids_diagnoses_num_per_100k&quot;  
## [11] &quot;borough&quot;</code></pre>
<pre class="r"><code>colnames(HIV_service)</code></pre>
<pre><code>## [1] &quot;unique_id&quot;    &quot;facilityname&quot; &quot;service_type&quot; &quot;address&quot;      &quot;borough&quot;     
## [6] &quot;state&quot;        &quot;zipcode&quot;      &quot;latitude&quot;     &quot;longitude&quot;</code></pre>
<p>Varialbes in the nyc_HIV1 and nyc_HIV2 Dataset</p>
<ul>
<li><code>year</code>: The year of data recording.</li>
<li><code>borough</code>: The borough in New York City.</li>
<li><code>neighbourhood</code>: The specific neighbourhood.</li>
<li><code>sex</code>: Gender of individuals.</li>
<li><code>race</code>: Racial category.</li>
<li><code>age</code>: Age of individuals.</li>
<li><code>hiv_diagnoses_num</code>: The number of new HIV
diagnoses.</li>
<li><code>hiv_diagnoses_num_per_100k</code>: The rate of new HIV
diagnoses per 100,000 population.</li>
<li><code>hiv_aids_concurrent_num</code>: The number of people diagnosed
with both HIV and AIDS concurrently.</li>
<li><code>concurrent_hiv_aids_among_all</code>: The proportion of HIV
diagnoses that are concurrent with an AIDS diagnosis.</li>
<li><code>aids_diagnoses_num</code>: The number of new AIDS
diagnoses.</li>
<li><code>aids_diagnoses_num_per_100k</code>: The rate of new AIDS
diagnoses per 100,000 population.</li>
</ul>
<p>Variables in the HIV_service datasets</p>
<ul>
<li><code>unique_id</code>: Identifier for the service resource.</li>
<li><code>facilityname</code>: Name of the facility offering HIV
services.</li>
<li><code>service_type</code>: Type of service provided.</li>
<li><code>address</code>, <code>borough</code>, <code>state</code>,
<code>zipcode</code>: Address details of the facility.</li>
<li><code>latitude</code>, <code>longitude</code>: Geographical
coordinates.</li>
</ul>
</div>
<div id="visualizations" class="section level1">
<h1>Visualizations</h1>
<div id="number-of-hivaids-diagnoses-by-race-sex-and-age-group."
class="section level2">
<h2><strong>Number of HIV/AIDS diagnoses by race, sex, and age
group.</strong></h2>
<pre class="r"><code>Female &lt;- nyc_HIV1 |&gt; 
  filter(sex == &quot;Female&quot; &amp; borough == &quot;All&quot; &amp; race !=&quot;All&quot;)

Male &lt;- nyc_HIV1 |&gt; 
  filter(sex == &quot;Male&quot;  &amp; borough == &quot;All&quot; &amp; race !=&quot;All&quot;)

graph1 = bind_rows(Female, Male)

nyc_HIV1$hiv_diagnoses_num &lt;- as.integer(nyc_HIV1$hiv_diagnoses_num)
nyc_HIV2$hiv_diagnoses_num &lt;- as.integer(nyc_HIV2$hiv_diagnoses_num)

age_summary &lt;- nyc_HIV2 |&gt; 
  filter(age != &quot;All&quot; &amp; race == &quot;All&quot; &amp; borough == &quot;All&quot;) |&gt; 
  group_by(age) |&gt; 
  summarise(total_hiv_diagnoses = sum(hiv_diagnoses_num))
# Graph Age 
ggplot(age_summary, aes(x = age, y = total_hiv_diagnoses)) +
  geom_bar(stat = &quot;identity&quot;, color = &quot;yellow&quot;, width = 0.7) +
  labs(title = &quot;Total HIV Diagnoses by Age Group&quot;,
       x = &quot;Age Group&quot;,
       y = &quot;Total HIV Diagnoses&quot;) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>invisible({ggplot(graph1, aes(x=race, y=hiv_diagnoses_num, fill=sex)) +
  geom_bar(stat=&quot;identity&quot;, position=position_dodge()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = &quot;Race&quot;, y = &quot;Number of HIV/AIDS Diagnoses&quot;, fill = &quot;Sex&quot;)})

Female &lt;- nyc_HIV1 |&gt; 
  filter(sex == &quot;Female&quot; &amp; borough == &quot;All&quot; &amp; race !=&quot;All&quot;)

Male &lt;- nyc_HIV1 |&gt; 
  filter(sex == &quot;Male&quot;  &amp; borough == &quot;All&quot; &amp; race !=&quot;All&quot;)

graph1 = bind_rows(Female, Male)

ggplot(graph1, aes(x=race, y=hiv_diagnoses_num, fill=sex)) +
  geom_bar(stat=&quot;identity&quot;, position=position_dodge()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = &quot;Race&quot;, y = &quot;Number of HIV/AIDS Diagnoses&quot;, fill = &quot;Sex&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>All &lt;- nyc_HIV1 %&gt;% 
  filter(sex == &quot;All&quot; &amp; race == &quot;All&quot; &amp; borough == &quot;All&quot;)</code></pre>
<p>summary: Both the nyc_HIV1 dataset and the nyc_HIV1 data have 11
variables, nyc_HIV1 is the data related to the number of patients with
HIV by gender and nyc_HIV2 is the data related to the number of patients
with HIV by age. When analyzing the number of HIV patients by race, the
results show that Latino/Hispanic races are used for high prevalence and
there are more males than females. When analyzing the number of HIV
patients by age group, the results showed that 20-29 year olds had the
highest number of total diagnoses and 13-19 year olds had the lowest
number of diagnoses.</p>
</div>
<div id="the-map-of-nyc-hiv-service-resources-location."
class="section level2">
<h2><strong>The map of NYC HIV service resources location.</strong></h2>
<pre class="r"><code>if (!require(leaflet)) install.packages(&#39;leaflet&#39;)
library(leaflet)
filtered_data = HIV_service[HIV_service$longitude != 0 &amp; HIV_service$latitude != 0,]

 leaflet(filtered_data) %&gt;%
  addProviderTiles(providers$OpenStreetMap) %&gt;%
  addCircleMarkers(
    ~longitude, ~latitude,
    radius = 4,
    popup = ~paste(&quot;&lt;strong&gt;Facility Name:&lt;/strong&gt;&quot;, facilityname,
                   &quot;&lt;br&gt;&lt;strong&gt;Service Type:&lt;/strong&gt;&quot;, service_type,
                   &quot;&lt;br&gt;&lt;strong&gt;Address:&lt;/strong&gt;&quot;, address,
                   &quot;&lt;br&gt;&lt;strong&gt;Borough:&lt;/strong&gt;&quot;, borough,
                   &quot;&lt;br&gt;&lt;strong&gt;Zip:&lt;/strong&gt;&quot;, zipcode)
  )</code></pre>
<div class="leaflet html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-8960b4245983c79223bf" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-8960b4245983c79223bf">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["OpenStreetMap",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircleMarkers","args":[[40.812995652745,40.812995652745,40.692099498968,40.692099498968,40.704241467553,40.704241467553,40.704241467553,40.704241467553,40.704241467553,40.704241467553,40.704241467553,40.704241467553,40.749981824279,40.749981824279,40.749981824279,40.749981824279,40.718695056809,40.820431122912,40.815783058945,40.820431122912,40.710504009675,40.692210017117,40.692210017117,40.692210017117,40.713942707565,40.745736372192,40.745736372192,40.820431122912,40.650441192176,40.825713139945,40.831713940554,40.851056840974,40.690785963931,40.686811992445,40.64933150274,40.64933150274,40.64933150274,40.640616897327,40.742898400573,40.704876808679,40.684310938797,40.754939423312,40.754939423312,40.754939423312,40.754939423312,40.754939423312,40.725611827473,40.651180767754,40.808040365309,40.808040365309,40.808040365309,40.808040365309,40.703568235835,40.703568235835,40.703568235835,40.703568235835,40.703568235835,40.703568235835,40.703568235835,40.822045578553,40.692210017117,40.692210017117,40.692210017117,40.692210017117,40.692210017117,40.677780690895,40.593305155465,40.816844910934,40.816844910934,40.706797802749,40.706797802749,40.743375576208,40.806515672405,40.708489788781,40.854649025463,40.745736372192,40.755784814414,40.755784814414,40.805511537162,40.805511537162,40.725556816186,40.725556816186,40.638021577661,40.638021577661,40.638021577661,40.638021577661,40.638021577661,40.751741613774,40.820720383685,40.745736372192,40.745736372192,40.646933783885,40.680487748092,40.680487748092,40.680487748092,40.75042554469,40.807340294602,40.807340294602,40.707263039205,40.841146178793,40.861293283489,40.861293283489,40.842362201727,40.704628796527],[-73.953848960606,-73.953848960606,-73.926656947232,-73.926656947232,-73.797920623078,-73.797920623078,-73.797920623078,-73.797920623078,-73.797920623078,-73.797920623078,-73.797920623078,-73.797920623078,-73.98620934121701,-73.98620934121701,-73.98620934121701,-73.98620934121701,-74.002463905081,-73.90473572366299,-73.925364032708,-73.90473572366299,-74.012523606424,-73.98666487882601,-73.98666487882601,-73.98666487882601,-73.983536664737,-73.994435007741,-73.994435007741,-73.90473572366299,-73.95766291167899,-73.90953020919299,-73.903754667953,-73.908002741372,-73.991825291648,-73.97570089792301,-73.96330702829199,-73.96330702829199,-73.96330702829199,-74.07570402076399,-74.002269928956,-74.015927292538,-73.90905575328701,-73.99217472339799,-73.99217472339799,-73.99217472339799,-73.99217472339799,-73.99217472339799,-74.00397585109801,-73.941711975605,-73.945273111172,-73.945273111172,-73.945273111172,-73.945273111172,-74.009853375369,-74.009853375369,-74.009853375369,-74.009853375369,-74.009853375369,-74.009853375369,-74.009853375369,-73.895877692433,-73.98666487882601,-73.98666487882601,-73.98666487882601,-73.98666487882601,-73.98666487882601,-73.937041465348,-73.791661188223,-73.920723980445,-73.920723980445,-73.941006713943,-73.941006713943,-73.990003579606,-73.94249293456301,-74.007477145324,-73.91062938531,-73.994435007741,-73.992250423011,-73.992250423011,-73.93806524980501,-73.93806524980501,-73.993487835491,-73.993487835491,-74.13188418811001,-74.13188418811001,-74.13188418811001,-74.13188418811001,-74.13188418811001,-73.990056458411,-73.89953977241299,-73.994435007741,-73.994435007741,-74.020929590199,-73.94957127177,-73.94957127177,-73.94957127177,-73.935323140695,-73.939483174823,-73.939483174823,-74.004313796717,-73.94269057404099,-73.906256825892,-73.906256825892,-73.890041350435,-73.91769846401399],4,null,null,{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":0.5,"fill":true,"fillColor":"#03F","fillOpacity":0.2},null,null,["<strong>Facility Name:<\/strong> African Services Committee, Inc. <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 429 West 127th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10027","<strong>Facility Name:<\/strong> African Services Committee, Inc. <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 429 West 127th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10027","<strong>Facility Name:<\/strong> After Hours Project <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 1204 Broadway <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11221","<strong>Facility Name:<\/strong> After Hours Project <br><strong>Service Type:<\/strong> Transitional & Short-term Housing Services <br><strong>Address:<\/strong> 1204 Broadway <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11221","<strong>Facility Name:<\/strong> AIDS Center of Queens County, Inc. <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 161-21 Jamaica Avenue <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11432","<strong>Facility Name:<\/strong> AIDS Center of Queens County, Inc. <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 161-21 Jamaica Avenue <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11432","<strong>Facility Name:<\/strong> AIDS Center of Queens County, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 161-21 Jamaica Avenue <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11432","<strong>Facility Name:<\/strong> AIDS Center of Queens County, Inc. <br><strong>Service Type:<\/strong> Housing Placement Services <br><strong>Address:<\/strong> 161-21 Jamaica Avenue <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11432","<strong>Facility Name:<\/strong> AIDS Center of Queens County, Inc. <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 161-21 Jamaica Avenue <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11432","<strong>Facility Name:<\/strong> AIDS Center of Queens County, Inc. <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 161-21 Jamaica Avenue <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11432","<strong>Facility Name:<\/strong> AIDS Center of Queens County, Inc. <br><strong>Service Type:<\/strong> Non-Medical Case Management <br><strong>Address:<\/strong> 161-21 Jamaica Avenue <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11432","<strong>Facility Name:<\/strong> AIDS Center of Queens County, Inc. <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 161-21 Jamaica Avenue <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11432","<strong>Facility Name:<\/strong> AIDS Service Center of Lower Manhattan, Inc. d/b/a Alliance for Positive Change <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 64 West 35th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10001","<strong>Facility Name:<\/strong> AIDS Service Center of Lower Manhattan, Inc. d/b/a Alliance for Positive Change <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 64 West 35th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10001","<strong>Facility Name:<\/strong> AIDS Service Center of Lower Manhattan, Inc. d/b/a Alliance for Positive Change <br><strong>Service Type:<\/strong> The Positive Life Workshop <br><strong>Address:<\/strong> 64 West 35th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10001","<strong>Facility Name:<\/strong> AIDS Service Center of Lower Manhattan, Inc. d/b/a Alliance for Positive Change <br><strong>Service Type:<\/strong> Transitional & Short-term Housing Services <br><strong>Address:<\/strong> 64 West 35th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10001","<strong>Facility Name:<\/strong> APICHA Community Health Center <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 400 Broadway <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10013","<strong>Facility Name:<\/strong> Argus Community, Inc. <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 760 East 160th Street <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10456","<strong>Facility Name:<\/strong> Argus Community, Inc. <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 226 East 144th Street <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10451","<strong>Facility Name:<\/strong> Argus Community, Inc. <br><strong>Service Type:<\/strong> Non-Medical Case Management <br><strong>Address:<\/strong> 760 East 160th Street <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10456","<strong>Facility Name:<\/strong> Assessment and Referral Team <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 150 Greenwich Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10007","<strong>Facility Name:<\/strong> Bailey House, Inc. <br><strong>Service Type:<\/strong> Housing Placement Services <br><strong>Address:<\/strong> 57 Willoughby Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11201","<strong>Facility Name:<\/strong> Bailey House, Inc. <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 57 Willoughby Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11201","<strong>Facility Name:<\/strong> Bailey House, Inc. <br><strong>Service Type:<\/strong> Transitional & Short-term Housing Services <br><strong>Address:<\/strong> 57 Willoughby Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11201","<strong>Facility Name:<\/strong> Betances Health Center <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 280 Henry Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10002","<strong>Facility Name:<\/strong> Beth Israel Medical Center <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 275 Seventh Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10011","<strong>Facility Name:<\/strong> Beth Israel Medical Center <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 275 Seventh Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10011","<strong>Facility Name:<\/strong> BOOM! Health <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 760 East 160th Street <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10456","<strong>Facility Name:<\/strong> Bridging Access to Care, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 2261 Church Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11226","<strong>Facility Name:<\/strong> Bronx Parent Housing Network, Inc. <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 488 East 164th Street <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10456","<strong>Facility Name:<\/strong> BronxCare Health System <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 1276 Fulton Avenue <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10456","<strong>Facility Name:<\/strong> BronxWorks, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 60 East Tremont Avenue <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10453","<strong>Facility Name:<\/strong> Brooklyn Legal Services, Inc. <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 105 Court Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11201","<strong>Facility Name:<\/strong> Brooklyn Plaza Medical Center, Inc <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 650 Fulton Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11217","<strong>Facility Name:<\/strong> CAMBA, Inc. <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 1720 Church Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11226","<strong>Facility Name:<\/strong> CAMBA, Inc. <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 1720 Church Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11226","<strong>Facility Name:<\/strong> CAMBA, Inc. <br><strong>Service Type:<\/strong> Transitional & Short-term Housing Services <br><strong>Address:<\/strong> 1720 Church Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11226","<strong>Facility Name:<\/strong> Community Health Action Of Staten Island, Inc. <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 56 Bay Street <br><strong>Borough:<\/strong> STATEN ISLAND <br><strong>Zip:<\/strong> 10301","<strong>Facility Name:<\/strong> Community Health Project, Inc. <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 356 West 18th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10011","<strong>Facility Name:<\/strong> Exponents, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 17 Battery Place <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10004","<strong>Facility Name:<\/strong> Family Services Network of New York <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 1420 Bushwick Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11207","<strong>Facility Name:<\/strong> Gay Men's Health Crisis, Inc. <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 307 West 38th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10018","<strong>Facility Name:<\/strong> Gay Men's Health Crisis, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 307 West 38th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10018","<strong>Facility Name:<\/strong> Gay Men's Health Crisis, Inc. <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 307 West 38th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10018","<strong>Facility Name:<\/strong> Gay Men's Health Crisis, Inc. <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 307 West 38th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10018","<strong>Facility Name:<\/strong> Gay Men's Health Crisis, Inc. <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 307 West 38th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10018","<strong>Facility Name:<\/strong> God's Love We Deliver, Inc. <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 166 Avenue of the Americas <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10013","<strong>Facility Name:<\/strong> Haitian Centers Council, Inc. <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 3807-3809 Church Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11203","<strong>Facility Name:<\/strong> Harlem United: Community AIDS Center, Inc. <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 306 Lenox Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10027","<strong>Facility Name:<\/strong> Harlem United: Community AIDS Center, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 306 Lenox Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10027","<strong>Facility Name:<\/strong> Harlem United: Community AIDS Center, Inc. <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 306 Lenox Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10027","<strong>Facility Name:<\/strong> Harlem United: Community AIDS Center, Inc. <br><strong>Service Type:<\/strong> Transitional & Short-term Housing Services <br><strong>Address:<\/strong> 306 Lenox Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10027","<strong>Facility Name:<\/strong> HHC Elmhurst Hospital Center <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 50 Water Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10038","<strong>Facility Name:<\/strong> HHC Harlem Hospital Center <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 50 Water Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10038","<strong>Facility Name:<\/strong> HHC Jacobi Medical Center <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 50 Water Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10038","<strong>Facility Name:<\/strong> HHC Kings County Hospital Center <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 50 Water Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10038","<strong>Facility Name:<\/strong> HHC North Central Bronx Hospital <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 50 Water Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10038","<strong>Facility Name:<\/strong> HHC Queens Hospital Center <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 50 Water Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10038","<strong>Facility Name:<\/strong> HHC Woodhull Medical and Mental Health Center <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 50 Water Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10038","<strong>Facility Name:<\/strong> Hispanic AIDS Forum, Inc. <br><strong>Service Type:<\/strong> Housing Placement Services <br><strong>Address:<\/strong> 975 Kelly Street <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10459","<strong>Facility Name:<\/strong> HIV Law Project, Inc. <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 57 Willoughby Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11201","<strong>Facility Name:<\/strong> Housing Works Health Services III <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 57 Willoughby Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11201","<strong>Facility Name:<\/strong> Housing Works, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 57 Willoughby Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11201","<strong>Facility Name:<\/strong> Housing Works, Inc. <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 57 Willoughby Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11201","<strong>Facility Name:<\/strong> Housing Works, Inc. <br><strong>Service Type:<\/strong> Transitional & Short-term Housing Services <br><strong>Address:<\/strong> 57 Willoughby Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11201","<strong>Facility Name:<\/strong> Interfaith Medical Center <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 1545 Atlantic Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11213","<strong>Facility Name:<\/strong> Joseph P. Addabbo Family Health Center, Inc. <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 6200 Beach Channel Drive <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11692","<strong>Facility Name:<\/strong> La Casa de Salud <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 324 East 149th Street <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10451","<strong>Facility Name:<\/strong> La Casa de Salud <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 324 East 149th Street <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10451","<strong>Facility Name:<\/strong> La Nueva Esperanza, Inc. <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 213 Johnson Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11206","<strong>Facility Name:<\/strong> La Nueva Esperanza, Inc. <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 213 Johnson Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11206","<strong>Facility Name:<\/strong> Latino Commission on AIDS, Inc. <br><strong>Service Type:<\/strong> The Positive Life Workshop <br><strong>Address:<\/strong> 24 West 25th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10010","<strong>Facility Name:<\/strong> Manhattan Legal Services <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 1 West 125th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10027","<strong>Facility Name:<\/strong> Mobilization for Justice, Inc. <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 100 William Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10038","<strong>Facility Name:<\/strong> Morris Heights Health Center <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 85 West Burnside Avenue <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10453","<strong>Facility Name:<\/strong> Mount Sinai Hospital <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 275 Seventh Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10011","<strong>Facility Name:<\/strong> New York Council on Adoptable Children, Inc. <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 333 West 39th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10018","<strong>Facility Name:<\/strong> New York Council on Adoptable Children, Inc. <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 333 West 39th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10018","<strong>Facility Name:<\/strong> New York Harm Reduction Educators, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 104-106 East 126th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10035","<strong>Facility Name:<\/strong> New York Harm Reduction Educators, Inc. <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 104-106 East 126th Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10035","<strong>Facility Name:<\/strong> Planned Parenthood of Greater New York, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 26 Bleecker Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10012","<strong>Facility Name:<\/strong> Planned Parenthood of Greater New York, Inc. <br><strong>Service Type:<\/strong> Non-Medical Case Management <br><strong>Address:<\/strong> 26 Bleecker Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10012","<strong>Facility Name:<\/strong> Project Hospitality, Inc. <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 100 Park Avenue <br><strong>Borough:<\/strong> STATEN ISLAND <br><strong>Zip:<\/strong> 10302","<strong>Facility Name:<\/strong> Project Hospitality, Inc. <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 100 Park Avenue <br><strong>Borough:<\/strong> STATEN ISLAND <br><strong>Zip:<\/strong> 10302","<strong>Facility Name:<\/strong> Project Hospitality, Inc. <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 100 Park Avenue <br><strong>Borough:<\/strong> STATEN ISLAND <br><strong>Zip:<\/strong> 10302","<strong>Facility Name:<\/strong> Project Hospitality, Inc. <br><strong>Service Type:<\/strong> Non-Medical Case Management <br><strong>Address:<\/strong> 100 Park Avenue <br><strong>Borough:<\/strong> STATEN ISLAND <br><strong>Zip:<\/strong> 10302","<strong>Facility Name:<\/strong> Project Hospitality, Inc. <br><strong>Service Type:<\/strong> Transitional & Short-term Housing Services <br><strong>Address:<\/strong> 100 Park Avenue <br><strong>Borough:<\/strong> STATEN ISLAND <br><strong>Zip:<\/strong> 10302","<strong>Facility Name:<\/strong> Services for the Underserved, Inc. <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 463 Seventh Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10018","<strong>Facility Name:<\/strong> St. Ann's Corner of Harm Reduction <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 886 Westchester Avenue <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10459","<strong>Facility Name:<\/strong> St. Luke's - Roosevelt Hospital <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 275 Seventh Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10001","<strong>Facility Name:<\/strong> St. Luke's - Roosevelt Hospital <br><strong>Service Type:<\/strong> Food and Nutrition <br><strong>Address:<\/strong> 275 Seventh Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10011","<strong>Facility Name:<\/strong> Sunset Park Health Council, Inc. <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 150 55th Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11220","<strong>Facility Name:<\/strong> The Family Center, Inc. <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 493 Nostrand Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11216","<strong>Facility Name:<\/strong> The Family Center, Inc. <br><strong>Service Type:<\/strong> Supportive Counseling Services <br><strong>Address:<\/strong> 493 Nostrand Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11216","<strong>Facility Name:<\/strong> The Family Center, Inc. <br><strong>Service Type:<\/strong> The Positive Life Workshop <br><strong>Address:<\/strong> 493 Nostrand Avenue <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11216","<strong>Facility Name:<\/strong> The Fortune Society, Inc. <br><strong>Service Type:<\/strong> Correctional Health Transitional Services <br><strong>Address:<\/strong> 29-76 Northern Boulevard <br><strong>Borough:<\/strong> QUEENS <br><strong>Zip:<\/strong> 11101","<strong>Facility Name:<\/strong> The Institute for Family Health <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 2006 Madison Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10035","<strong>Facility Name:<\/strong> The Institute for Family Health <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 2006 Madison Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10035","<strong>Facility Name:<\/strong> The Legal Aid Society <br><strong>Service Type:<\/strong> Legal Services <br><strong>Address:<\/strong> 199 Water Street <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10038","<strong>Facility Name:<\/strong> The New York and Presbyterian Hospital <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 177 Fort Washington Avenue <br><strong>Borough:<\/strong> MANHATTAN <br><strong>Zip:<\/strong> 10032","<strong>Facility Name:<\/strong> Tolentine Zeiser Community Life Center <br><strong>Service Type:<\/strong> Harm Reduction Services <br><strong>Address:<\/strong> 2331 University Avenue <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10468","<strong>Facility Name:<\/strong> Tolentine Zeiser Community Life Center <br><strong>Service Type:<\/strong> Housing Placement Services <br><strong>Address:<\/strong> 2331 University Avenue <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10468","<strong>Facility Name:<\/strong> Vocational Instruction Project Community Services, Inc. <br><strong>Service Type:<\/strong> Mental Health Services <br><strong>Address:<\/strong> 770 East 176 Street <br><strong>Borough:<\/strong> BRONX <br><strong>Zip:<\/strong> 10460","<strong>Facility Name:<\/strong> Wyckoff Heights Medical Center <br><strong>Service Type:<\/strong> Care Coordination <br><strong>Address:<\/strong> 374 Stockholm Street <br><strong>Borough:<\/strong> BROOKLYN <br><strong>Zip:<\/strong> 11237"],null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[40.593305155465,40.861293283489],"lng":[-74.13188418811001,-73.791661188223]}},"evals":[],"jsHooks":[]}</script>
<p>summary: Here, an interactive map was created using the leaflet
package to visualize the distribution of HIV service facilities and
detailed information to help better understand the allocation of
resources for HIV prevention and treatment.</p>
</div>
<div id="distribution-of-the-hivaids-diagnoses-by-neighborhood."
class="section level2">
<h2><strong>Distribution of the HIV/AIDS diagnoses by
neighborhood.</strong></h2>
<pre class="r"><code>#work
# I&#39;ll see if I can find the log&amp;lat for the neighborhoods
diagnoses &lt;- nyc_HIV1 %&gt;% 
  select(borough, hiv_diagnoses_num)

# Plot bar chart
ggplot(diagnoses, aes(x = reorder(borough, hiv_diagnoses_num), y = hiv_diagnoses_num)) +
  geom_col() +
  labs(x = &quot;Neighborhood&quot;,
       y = &quot;Number of HIV Diagnoses&quot;,
       title = &quot;HIV Diagnoses by Neighborhood&quot;) +
  coord_flip()</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>summary: The number of HIV cases varies by community, with the Staten
Island community having a much smaller number of confirmed cases, the
Brooklyn community having a larger number of confirmed cases, and the
other communities having a similar number of cases.</p>
</div>
<div
id="trend-analysisanalyze-the-trend-of-the-number-of-hivaids-diagnoses-over-time."
class="section level2">
<h2><strong>Trend analysis:analyze the trend of the number of HIV/AIDS
diagnoses over time.</strong></h2>
<pre class="r"><code>All &lt;- nyc_HIV1 %&gt;% 
  filter(sex == &quot;All&quot; &amp; race == &quot;All&quot; &amp; borough == &quot;All&quot;)

# Plot diagnoses over time
ggplot(All, aes(x = year, y = hiv_diagnoses_num)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, se = FALSE) + 
  labs(
    title = &quot;HIV Diagnoses Trend (All Sex)&quot;,
    x = &quot;Year&quot;,
    y = &quot;Number of Diagnoses&quot;
  )</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>summary: The number of patients diagnosed in different years showed
significant differences. The overall trend is decreasing from year to
year. This also reflects the growing importance that has been placed on
HIV.</p>
</div>
</div>
<div id="exploratory-statistical-analyses" class="section level1">
<h1>Exploratory statistical analyses</h1>
<p><strong>Correlation analysis:After the Visualizations is there any
association between different variables such as neighborhood, age,
gender, and race.</strong></p>
<p><strong>T-test for HPV prevalence in gender-specific
populations.</strong></p>
<pre class="r"><code>nyc_HIV1$hiv_diagnoses_num &lt;- as.numeric(nyc_HIV1$hiv_diagnoses_num)

# Extracting data for females and males
female_data &lt;- na.omit(nyc_HIV1[nyc_HIV1$sex == &quot;Female&quot;,]$hiv_diagnoses_num)
male_data &lt;- na.omit(nyc_HIV1[nyc_HIV1$sex == &quot;Male&quot;,]$hiv_diagnoses_num)

# Perform T-test
t.test(female_data, male_data)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  female_data and male_data
## t = -8.183, df = 1921.9, p-value = 4.982e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -25.78465 -15.81460
## sample estimates:
## mean of x mean of y 
##  6.138889 26.938515</code></pre>
<p>summary: The t-test passed the test of significance indicating that
there was a significant difference in the number of males and females
with HIV.</p>
<p><strong>Test whether “hiv_diagnoses_num” is significantly different
across ethnicities.</strong></p>
<pre class="r"><code>anova1 &lt;- anova(lm(hiv_diagnoses_num ~ race, data = nyc_HIV1))
print(anova1)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: hiv_diagnoses_num
##             Df   Sum Sq Mean Sq F value    Pr(&gt;F)    
## race         5  2587921  517584  59.623 &lt; 2.2e-16 ***
## Residuals 5173 44906405    8681                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>summary: The ANOVA passed the test of significance, indicating that
there is indeed a significant difference in the number of people of
different races who have HIV.</p>
<p><strong>Test whether “hiv_diagnoses_num” is significantly different
between age groups.</strong></p>
<pre class="r"><code>anova2 &lt;- anova(lm(hiv_diagnoses_num ~ age, data = nyc_HIV2))
print(anova2)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: hiv_diagnoses_num
##              Df   Sum Sq Mean Sq F value    Pr(&gt;F)    
## age           6  2603171  433862  178.22 &lt; 2.2e-16 ***
## Residuals 10569 25729234    2434                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>summary: The ANOVA passed the test of significance indicating that
there is a significant difference in the number of HIV in different age
groups.</p>
<p><strong>Test whether there is a significant difference between people
of different races and different age groups.</strong></p>
<pre class="r"><code>race_table &lt;- table(nyc_HIV1$race, nyc_HIV1$sex)
race_table</code></pre>
<pre><code>##                          
##                           All Female Male
##   All                     288    288  288
##   Asian/Pacific\nIslander 288    288  288
##   Black                   288    288  288
##   Latino/Hispanic         288    288  288
##   Other/Unknown           288    288  288
##   White                   288    288  288</code></pre>
<pre class="r"><code># Perform chi-square test
chisq.test(race_table)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  race_table
## X-squared = 0, df = 10, p-value = 1</code></pre>
<p>summary: The chi-square test passes the test of significance,
indicating that there is a significant relationship between race and
gender.</p>
<div id="linear-regression-analysis" class="section level2">
<h2>Linear regression analysis</h2>
<pre class="r"><code># Defining a Unique Thermal Coding Processor
library(caret)
encoder &lt;- dummyVars(~ borough + sex + race, data = nyc_HIV1)
# Solo thermal coding of data
encoded_data &lt;- predict(encoder, newdata = nyc_HIV1)
# Merging the coded and original data sets
nyc_HIV3 &lt;- cbind(nyc_HIV1, encoded_data)
nyc_HIV4&lt;-nyc_HIV3[,-c(2,3,4,5,7,8,9,10,11,12,18,21)]
model &lt;- lm(hiv_diagnoses_num ~. , data = nyc_HIV4)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = hiv_diagnoses_num ~ ., data = nyc_HIV4)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -354.01  -15.87   -3.06   10.01 1637.59 
## 
## Coefficients:
##                                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                    4514.4981  1597.6302   2.826  0.00474 ** 
## year                             -2.0224     0.7912  -2.556  0.01062 *  
## boroughBronx                   -354.5277     7.8099 -45.395  &lt; 2e-16 ***
## boroughBrooklyn                -358.4969     7.6619 -46.789  &lt; 2e-16 ***
## boroughManhattan               -362.8923     7.6887 -47.198  &lt; 2e-16 ***
## boroughQueens                  -363.2155     7.6887 -47.240  &lt; 2e-16 ***
## `boroughStaten\\nIsland`       -373.2117     8.0652 -46.274  &lt; 2e-16 ***
## sexFemale                       -26.8822     2.6030 -10.327  &lt; 2e-16 ***
## sexMale                          -6.1453     2.6045  -2.359  0.01834 *  
## `raceAsian/Pacific\\nIslander`  -62.6910     3.6817 -17.028  &lt; 2e-16 ***
## raceBlack                       -36.4375     3.6807  -9.900  &lt; 2e-16 ***
## `raceLatino/Hispanic`           -41.7176     3.6807 -11.334  &lt; 2e-16 ***
## `raceOther/Unknown`             -65.3393     3.6850 -17.731  &lt; 2e-16 ***
## raceWhite                       -57.9514     3.6807 -15.745  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 76.5 on 5165 degrees of freedom
##   (5 observations deleted due to missingness)
## Multiple R-squared:  0.3635, Adjusted R-squared:  0.3619 
## F-statistic: 226.9 on 13 and 5165 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>summary: The coefficients of all variables passed the significance
test, indicating that all of these independent variables have a
significant effect on hiv_diagnoses_num. The coefficient before the
variable “boroughStaten\” has the largest absolute value, which means
that it has the largest effect on the number of HIV patients. In
addition, the coefficients before these variables are all negative,
indicating that they all negatively affect hiv_diagnoses_num.Finally,
the multiple linear regression model constructed
ishiv_diagnoses_num=4514.4981-2.0224<em>year-354.5227</em>boroughBronx-358.4969<em>boroughBrooklyn-362.8923</em>boroughManhattan-363.2155<em>boroughQueens-373.2117</em>boroughStaten\nIsland-26.8822<em>sexFemale-6.1453</em>sexMale-62.6910<em>raceAsian
/Pacific\nIslander-36.4375</em>raceBlack-41.7176<em>raceLatino/Hispanic-65.3393</em>raceOther/Unknown-57.9514*raceWhite.</p>
</div>
<div id="regression-model-test" class="section level2">
<h2>Regression model test</h2>
<pre class="r"><code>#Drawing demonstration
par(mfrow=c(2, 2))  
plot(model)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code># Plot of predicted values against residuals
residuals &lt;- resid(model)
fitted_values &lt;- predict(model)
plot(fitted_values, residuals,
     xlab = &quot;Fitted values&quot;,
     ylab = &quot;Residuals&quot;,
     main = &quot;Residuals vs. Fitted&quot;)
abline(h = 0, col = &quot;red&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-14-2.png" width="672" /></p>
<p><strong>summary:Here is a test of the effectiveness of the regression
model constructed above. Use plot(model) to draw residual plots, scatter
plots and other diagnostic plots. Residual plots are used to check for
linear properties, heteroskedasticity, outliers, etc. Scatter plots can
be used to check for correlation between independent variables, and QQ
plots are used to check whether the residuals conform to the assumption
of normal distribution. Here, we can see that the residuals do not
conform well to normality and randomness. Analyzing the reason, it may
be due to the existence of individual outliers, which affects the
distribution of the data and the distribution of the residuals, making
them not conform to normality and randomness.</strong></p>
<p><strong>if github md knit fail,change to the html
output“</strong></p>
</div>
</div>
<div id="results" class="section level1">
<h1>Results</h1>
<div id="gender-differences-in-hiv-prevalence" class="section level2">
<h2>Gender Differences in HIV Prevalence</h2>
<p>A Welch Two Sample t-test was conducted to compare the prevalence of
HIV diagnoses between female and male populations. The analysis revealed
a statistically significant difference in the number of HIV diagnoses
between females (<span class="math inline">\(\bar{x} = 6.14\)</span>)
and males (<span class="math inline">\(\bar{x} = 26.94\)</span>), <span
class="math inline">\(t(1921.9) = -8.183\)</span>, <span
class="math inline">\(p &lt; .00001\)</span>. The 95% confidence
interval for the difference in means ranged from -25.78 to -15.81,
indicating a higher prevalence of HIV diagnoses in males compared to
females.</p>
</div>
<div id="hiv-diagnoses-across-ethnicities" class="section level2">
<h2>HIV Diagnoses Across Ethnicities</h2>
<p>An Analysis of Variance (ANOVA) was performed to examine whether the
number of HIV diagnoses significantly differed across various ethnic
groups. The results indicated a significant effect of race on the number
of HIV diagnoses, <span class="math inline">\(F(5, 5173) =
59.623\)</span>, <span class="math inline">\(p &lt; .00001\)</span>.
This finding suggests substantial disparities in HIV diagnoses among
different racial groups.</p>
</div>
<div id="hiv-prevalence-among-different-age-groups"
class="section level2">
<h2>HIV Prevalence Among Different Age Groups</h2>
<p>Further, an ANOVA was conducted to assess the impact of age on HIV
diagnoses. The analysis showed a significant difference in the number of
HIV diagnoses among different age groups, <span
class="math inline">\(F(6, 10569) = 178.22\)</span>, <span
class="math inline">\(p &lt; .00001\)</span>. This result highlights the
varying prevalence of HIV across age demographics.</p>
<p>These findings collectively offer valuable insights into the
epidemiological patterns of HIV diagnoses in New York City, highlighting
significant disparities based on gender, race, and age. Such disparities
underscore the need for targeted public health interventions and
policies to address the unique needs of these demographic groups.</p>
</div>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<div id="findings-from-the-analysis" class="section level2">
<h2>Findings from the Analysis</h2>
<ul>
<li>Gender and HIV Prevalence: There tends to be a difference in HIV
infection rates and diagnosis numbers between males and females.In the
analysis we conducted, it was found that the number of HIV diagnoses was
significantly higher in males compared to females.</li>
<li>Ethnic Disparities in HIV Diagnoses: Our ANOVA tests revealed
significant differences in HIV diagnoses among different races and age
groups,emphasizing the persistence of inequities in HIV prevalence.</li>
<li>Variation Across Boroughs: The linear regression analysis showed
significant differences in HIV diagnoses among the boroughs of New York
City. Boroughs like Staten Island exhibited the largest negative
coefficients in the model, indicating a lower number of HIV diagnoses
compared to other regions. The differences are possibly influenced by
factors such as local public health policies, access to healthcare
services, and community-level prevention efforts.</li>
<li>Trends in HIV Infections: Our analysis indicated an 31% decrease in
new HIV infections from 2017 to 2021, suggesting a gradual but steady
progress in controlling new infections.</li>
</ul>
</div>
<div id="insights-and-reflections" class="section level2">
<h2>Insights and Reflections</h2>
<p>Our findings provide critical insights into the multifaceted nature
of HIV epidemiology in New York City. The results underscore the
necessity of addressing social and structural factors, such as racism,
sexism, economic factors, homophobia, and transphobia. These
determinants can influence risk behaviors, access to healthcare, and
overall health outcomes.</p>
<p>While some findings, such as the disparities in HIV diagnoses among
different demographics, were expected, the impact of external factors
like the COVID-19 pandemic on the patterns of HIV diagnoses was
particularly intriguing. It highlights the dynamic nature of public
health challenges and the need for adaptive and resilient healthcare
systems.</p>
<p>The insights gained from this analysis can aid in the development of
more nuanced and effective public health strategies. These strategies
should not only be responsive to the unique needs of different
demographics but also adaptable to the specific challenges faced by each
borough and race. By addressing these multifaceted aspects, New York
City can continue to make progress towards reducing HIV infections and
improving outcomes for people living with HIV.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
